name: zam_block_architecture
version: 0.3.0
description: Architecture that bridges the gap between Business Analysts and Developers.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_block_architecture

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  zam_command_pattern: ^0.3.0
  zam_core: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  zam_test: ^0.5.0
